import {filterPlaces,inGeometry,meters} from './engine.js?v=2';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}};
const presets={cityhall:[-75.1636,39.9526],university:[-75.1988,39.9530],south:[-75.1697,39.9277],north:[-75.1579,39.9811],northeast:[-75.0835,40.0176]};
function storageGet(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function storageSet(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}}
let places=[],areas=[],roads,city,manifest,routes={},visible=[],path=[],active=null,version=0,ready=false,busy=true,routeUnavailable=false,pick=false,limitRows=30,areaId=null;
const state={query:'',category:'all',snap:false,tab:'explore',mode:'drive',limit:15,radius:3,sort:'distance',area:null};
const saved=new Set(storageGet('fieldfare.saved',[]));let origin=[...presets.cityhall],center=[...origin],scale=26000,events=[],consent=false;
const canvas=$('#map'),ctx=canvas.getContext('2d');let width=0,height=0,pins=[],drag=null,moved=false,frame=0;
// Ordinary wheel gestures scroll the page. Only Ctrl+wheel opts into map zoom.
canvas.addEventListener('wheel',e=>{if(!e.ctrlKey)e.stopImmediatePropagation();},{passive:true});
const worker=new Worker('./route-worker.js?v=2',{type:'module'});
function track(name,props={}){if(consent)events.push({name,at:new Date().toISOString(),...props});}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3200);}
function project(p){return [(p[0]-center[0])*scale*.767+width/2,(center[1]-p[1])*scale+height/2];}
function unproject(p){return [(p[0]-width/2)/(scale*.767)+center[0],center[1]-(p[1]-height/2)/scale];}
function scheduleDraw(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);}
function line(points,color,lineWidth){if(points.length<2)return;ctx.beginPath();points.forEach((p,i)=>{const [x,y]=project(p);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.strokeStyle=color;ctx.lineWidth=lineWidth;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function polygon(geometry,fill,stroke){const polys=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;ctx.beginPath();for(const poly of polys)for(const ring of poly){ring.forEach((p,i)=>{const [x,y]=project(p);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.closePath();}if(fill){ctx.fillStyle=fill;ctx.fill('evenodd');}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.7;ctx.stroke();}}
function draw(){if(!roads||!width)return;ctx.clearRect(0,0,width,height);ctx.fillStyle='#dce6dd';ctx.fillRect(0,0,width,height);polygon(city,'#eceee3',null);
 const northwest=unproject([-100,-100]),southeast=unproject([width+100,height+100]);
 for(const a of areas){if(a.bounds[2]<northwest[0]||a.bounds[0]>southeast[0]||a.bounds[3]<southeast[1]||a.bounds[1]>northwest[1])continue;
  const selected=a.id===(areaId||state.area);polygon(a.geometry,selected?'#dce4bd':state.tab==='areas'?`rgba(115,139,85,${Math.min(.30,.03+(a.count||0)*.008)})`:null,state.tab==='areas'?'#acbba0':'#dfe4d7');}
 for(const major of [false,true]){ctx.beginPath();for(const [ns,,kind] of roads.ways){if((!['residential','unclassified','living_street'].includes(kind))!==major)continue;const mid=roads.nodes[ns[Math.floor(ns.length/2)]];if(mid[0]<northwest[0]||mid[0]>southeast[0]||mid[1]<southeast[1]||mid[1]>northwest[1])continue;ns.forEach((n,i)=>{const [x,y]=project(roads.nodes[n]);if(!i)ctx.moveTo(x,y);else ctx.lineTo(x,y);});}ctx.strokeStyle=major?'#fffdf5':'#fafbf5';ctx.lineWidth=major?Math.max(2,scale/21000):Math.max(.8,scale/38000);ctx.stroke();}
 // Geographic context labels; all coordinates are fixed labels, not inferred demand.
 ctx.textAlign='center';for(const [name,p] of [['CENTER CITY',[-75.164,39.959]],['UNIVERSITY CITY',[-75.2,39.956]],['SOUTH PHILADELPHIA',[-75.169,39.928]],['NORTHERN LIBERTIES',[-75.14,39.966]],['OLD CITY',[-75.143,39.95]],['FAIRMOUNT',[-75.177,39.969]]]){const [x,y]=project(p);ctx.font='600 9px sans-serif';ctx.fillStyle='#8c9b80';ctx.fillText(name,x,y);}
 if(state.mode==='drive'&&path.length){line(path,'#fdfcf4',7);line(path,'#4c7656',3.5);ctx.setLineDash([3,4]);line([origin,path[0]],'#b5974e',2);const p=places.find(p=>p.id===active);if(p)line([path[path.length-1],p.point],'#b5974e',2);ctx.setLineDash([]);}
 pins=[];const plotted=visible.slice(0,100);if(active&&!plotted.some(p=>p.id===active)){const p=places.find(p=>p.id===active);if(p)plotted.push(p);}
 plotted.forEach((p,i)=>{const [x,y]=project(p.point);if(x<-20||x>width+20||y<-20||y>height+20)return;const chosen=p.id===active,r=chosen?16:12;ctx.beginPath();ctx.arc(x,y,r+3,0,Math.PI*2);ctx.fillStyle='#ffffffb8';ctx.fill();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=chosen?'#284f3d':saved.has(p.id)?'#ba963e':'#75895b';ctx.fill();ctx.font=`600 ${chosen?11:9}px sans-serif`;ctx.fillStyle='#fff';ctx.textBaseline='middle';ctx.fillText(String(i+1),x,y+.3);pins.push({x,y,p});});
 const [ox,oy]=project(origin);ctx.beginPath();ctx.arc(ox,oy,15,0,Math.PI*2);ctx.fillStyle='#cfb05b35';ctx.fill();ctx.beginPath();ctx.arc(ox,oy,7,0,Math.PI*2);ctx.fillStyle='#ba913a';ctx.fill();ctx.strokeStyle='#fffaf0';ctx.lineWidth=3;ctx.stroke();ctx.textBaseline='alphabetic';
 // A real ground-distance scale, adjusted for latitude.
 const scaleMeters=[50,100,200,500,1000,2000].filter(m=>m/111195*scale<=80).at(-1)||50,span=scaleMeters/111195*scale;ctx.strokeStyle='#76836a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(width-100,height-51);ctx.lineTo(width-100+span,height-51);ctx.stroke();ctx.fillStyle='#76836a';ctx.font='8px sans-serif';ctx.fillText(scaleMeters>=1000?`${scaleMeters/1000} km`:`${scaleMeters} m`,width-100+span/2,height-56);
}
function resize(){const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(2,devicePixelRatio);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);scheduleDraw();}new ResizeObserver(resize).observe(canvas);
function compute(){busy=!routeUnavailable;version++;path=[];active=null;$('#detail').hidden=true;routes=Object.fromEntries(places.map(p=>[p.id,{direct:meters(origin,p.point),distance:null,minutes:null}]));if(ready)worker.postMessage({type:'compute',origin,version});render();}
function routeFallback(){busy=false;ready=false;routeUnavailable=true;state.mode='nearby';routes=Object.fromEntries(places.map(p=>[p.id,{direct:meters(origin,p.point),distance:null,minutes:null}]));syncMode();render();toast('Road routing unavailable. Showing straight-line proximity.');}
worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;routeUnavailable=false;compute();}else if(data.type==='routes'&&data.version===version){routes=data.routes;busy=false;render();if(active)showDetail(active,false);if(data.originConnector>150)toast('No nearby road node. Choose another start or use nearby distance.');}else if(data.type==='path'&&data.version===version&&data.id===active){path=data.points;scheduleDraw();}else if(data.type==='error'){routeFallback();}};
worker.onerror=routeFallback;
function journey(p){const r=routes[p.id];if(!r)return 'Calculating…';if(state.mode==='nearby')return `${(r.direct/1000).toFixed(1)} km direct`;return r.distance===null?'No route estimate':`${Math.ceil(r.minutes)} min estimate`;}
function render(){visible=filterPlaces(places,state,routes,saved);$('#saved-count').textContent=saved.size;$('#results-title').textContent=state.tab==='saved'?'Your saved places':state.area?'Places in this area':'Places within reach';$('#status').textContent=busy?'Calculating routes on the historical road network…':`${visible.length.toLocaleString()} places · ${state.mode==='drive'?'modeled drive budget':'straight-line distance'}${state.tab==='saved'?' · current filters apply':''}`;
 $('#area-filter').hidden=!state.area;$('#area-filter').innerHTML=state.area?`Tract ${escape(state.area)} <button id="clear-area" aria-label="Clear area filter">Clear ×</button>`:'';$('#clear-area')?.addEventListener('click',()=>{state.area=null;render();});
 $('#results').innerHTML=visible.slice(0,limitRows).map((p,i)=>`<article class="place-card ${p.id===active?'active':''}" data-place="${escape(p.id)}"><span class="card-num">${i+1}</span><button class="card-main" data-open="${escape(p.id)}"><h3>${escape(p.name)}</h3><p>${escape(p.address||'Address not supplied')} ${escape(p.zip)}</p><div class="badges"><span class="badge">${escape(p.category)}</span>${p.snap==='historical'?'<span class="badge snap">SNAP · historical</span>':''}</div><div class="card-meta"><strong>${journey(p)}</strong><span>${p.completeness}/6 info fields</span></div></button><button class="save ${saved.has(p.id)?'is-saved':''}" data-save="${escape(p.id)}" aria-label="${saved.has(p.id)?'Unsave':'Save'} ${escape(p.name)}" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'★':'☆'}</button></article>`).join('');
 if(!visible.length&&!busy)$('#results').innerHTML=`<div class="empty"><strong>${state.tab==='saved'&&!saved.size?'A little planning goes a long way.':'No places match this search.'}</strong>${state.tab==='saved'&&!saved.size?'Save a store using the star, then compare it here.':'Try a wider travel budget, a different category, or a nearby starting point.'}<button id="reset-filters">${state.tab==='saved'?'Explore places':'Reset filters'}</button></div>`;
 $$('[data-open]').forEach(b=>b.addEventListener('click',()=>showDetail(b.dataset.open)));$$('[data-save]').forEach(b=>b.addEventListener('click',()=>toggleSave(b.dataset.save)));$('#reset-filters')?.addEventListener('click',reset);
 $('#more').hidden=visible.length<=limitRows;$('#area-panel').hidden=state.tab!=='areas';if(state.tab==='areas')renderArea();scheduleDraw();}
function toggleSave(id){const added=!saved.has(id);if(added)saved.add(id);else saved.delete(id);storageSet('fieldfare.saved',[...saved]);track(added?'save_place':'unsave_place');render();if(active===id)showDetail(id,false);toast(added?'Saved to your local shortlist':'Removed from saved places');}
function showDetail(id,log=true){const p=places.find(p=>p.id===id);if(!p)return;active=id;const r=routes[id],website=safeURL(p.website);$('#detail').hidden=false;$('#area-panel').hidden=true;
 const url=new URL('https://www.google.com/maps/dir/');url.searchParams.set('api','1');url.searchParams.set('destination',`${p.point[1]},${p.point[0]}`);url.searchParams.set('travelmode','driving');url.searchParams.set('origin',`${origin[1]},${origin[0]}`);
 $('#detail').innerHTML=`<button class="close" aria-label="Close place details">×</button><span class="detail-top">${escape(p.category)} · PLACE PROFILE</span><h2>${escape(p.name)}</h2><p class="address">${escape(p.address||'Address unavailable')} ${escape(p.zip)}</p><div class="badges">${p.snap==='historical'?'<span class="badge snap">Listed in historical SNAP file</span>':'<span class="badge">SNAP status unknown</span>'}<span class="badge">${p.completeness}/6 fields supplied</span></div><div class="journey"><div><strong>${r?(state.mode==='drive'&&r.distance!==null?Math.ceil(r.minutes)+' min':(r.direct/1000).toFixed(1)+' km'):'—'}</strong><br><span>${state.mode==='drive'&&r?.distance!==null?'Modeled drive + parking':'Straight-line distance'}</span></div><span>${r?.distance!=null?(r.distance/1000).toFixed(1)+' km road + connectors':'Road estimate unavailable'}</span></div><dl><dt>HOURS · SOURCE TEXT, NOT LIVE</dt><dd>${escape(p.hours||'Not supplied — check before visiting')}</dd><dt>CONTACT</dt><dd>${p.phone?escape(p.phone):'Phone not supplied'}${website?`<br><a href="${escape(website)}" target="_blank" rel="noopener noreferrer">Visit store website ↗</a>`:''}</dd><dt>ACCESS INFORMATION</dt><dd>${p.wheelchair?'Wheelchair tag: '+escape(p.wheelchair)+' (historical, unverified)':'Wheelchair access not supplied'}</dd><dt>SOURCES & VINTAGE</dt><dd>${escape(p.sources.join(' + '))}<br>${escape(p.vintage)}${p.checkDate?'<br>Source check_date: '+escape(p.checkDate):''}${p.matchStatus?'<br>Cross-source link is provisional.':''}</dd></dl><p class="detail-note">${state.mode==='drive'?'Estimate uses 25 km/h + 5 min parking; no traffic or turn-restriction model. ':''}Historical listing does not confirm current opening or SNAP participation. ${p.geometryMethod.includes('vertex')?'Map point represents a building, not a verified entrance.':''}</p><a class="primary" id="directions" href="${escape(url.href)}" target="_blank" rel="noopener noreferrer">Check directions in Google Maps ↗</a><button class="secondary" id="detail-save">${saved.has(id)?'★ Saved — remove':'☆ Save to shortlist'}</button><button class="secondary" id="report">Flag information for review</button>`;
 $('#detail .close').onclick=()=>{active=null;path=[];$('#detail').hidden=true;render();};$('#detail-save').onclick=()=>toggleSave(id);$('#directions').onclick=()=>track('directions_click',{mode:state.mode});$('#report').onclick=()=>reportPlace(p);if(log)track('place_detail_open',{category:p.category});if(ready&&!busy)worker.postMessage({type:'path',id,version});render();if(state.tab==='areas')$('#area-panel').hidden=true;}
function reportPlace(p){openModal(`<h2>Help make the picture clearer.</h2><p>Save a review note for <strong>${escape(p.name)}</strong>. This prototype stores feedback in this browser only; nothing is sent to a business or data provider.</p><label for="issue-type">What needs a closer look?</label><p><select id="issue-type"><option>Address or map point</option><option>Store name or duplicate</option><option>SNAP information</option><option>Hours or contact information</option></select></p><button id="save-report" class="primary">Save local review flag</button>`);$('#save-report').onclick=()=>{const flags=storageGet('fieldfare.reviews',[]);flags.push({id:p.id,issue:$('#issue-type').value,date:new Date().toISOString(),status:'pending'});storageSet('fieldfare.reviews',flags);track('review_flag');$('#modal').close();toast('Review flag saved locally — not submitted externally');};}
function renderArea(){const a=areas.find(a=>a.id===(areaId||state.area))||areas.find(a=>inGeometry(origin,a.geometry))||areas[0];areaId=a.id;const items=places.filter(p=>p.area===a.id),routed=items.filter(p=>routes[p.id]?.minutes!=null&&routes[p.id].minutes<=state.limit).length;$('#area-panel').innerHTML=`<span class="detail-top">AREA INSIGHTS / CENSUS TRACT</span><h3>One area. Many food journeys.</h3><select id="area-select" aria-label="Select census tract">${areas.map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>Tract ${x.id} · ${x.count} observed places</option>`).join('')}</select><div class="area-stats"><div><strong>${items.length}</strong><span>observed POIs</span></div><div><strong>${items.filter(p=>p.snap==='historical').length}</strong><span>historical SNAP</span></div><div><strong>${routed}</strong><span>within ${state.limit} min*</span></div></div><p>*Modeled drive from your starting point. These are snapshot counts, not true market coverage or an area quality score.</p><button class="primary" id="browse-area">Explore this area's stores →</button>`;$('#area-select').onchange=e=>{areaId=e.target.value;const area=areas.find(a=>a.id===areaId);center=[(area.bounds[0]+area.bounds[2])/2,(area.bounds[1]+area.bounds[3])/2];renderArea();scheduleDraw();};$('#browse-area').onclick=()=>{state.area=areaId;setTab('explore');track('area_browse');};}
function setTab(tab){state.tab=tab;active=null;path=[];$('#detail').hidden=true;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('#map-heading').textContent=tab==='areas'?'See the area behind the places.':tab==='saved'?'A shortlist for your next stop.':'Start close. Discover more.';$('#map-hint').textContent=tab==='areas'?'Click an area to inspect its food supply':'Click a numbered place to explore';track('tab_change',{tab});render();}
function reset(){Object.assign(state,{query:'',category:'all',snap:false,area:null,tab:'explore'});areaId=null;center=[...origin];$('#search').value='';$('#category').value='all';$('#snap').checked=false;setTab('explore');}
function syncMode(){$$('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===state.mode));$('#limit').min=state.mode==='drive'?10:1;$('#limit').max=state.mode==='drive'?30:10;$('#limit').step=state.mode==='drive'?5:1;$('#limit').value=state.mode==='drive'?state.limit:state.radius;$('#limit-label').textContent=state.mode==='drive'?'Travel budget':'Search radius';$('#limit-value').textContent=state.mode==='drive'?`${state.limit} min`:`${state.radius} km`;$('#travel-note').textContent=state.mode==='drive'?'Road distance at 25 km/h + 5 min parking. No live traffic.':'Straight-line distance only. Not a walking route or travel time.';$('#legend-mode').textContent=state.mode==='drive'?'Directed driving network':'Straight-line proximity';}
function openModal(html){$('#modal-body').innerHTML=html;$('#modal').showModal();}
function about(){openModal(`<div class="eyebrow">THE EVIDENCE BEHIND THE EXPERIENCE</div><h2>A field guide, with its sources.</h2><div class="metric-grid"><div><strong>${manifest.poiCount}</strong>place records</div><div><strong>${manifest.areaCount}</strong>census tracts</div><div><strong>${manifest.provisionalMatches}</strong>provisional links</div></div><h3>Historical public snapshots</h3><p>USDA SNAP: 2004–2024 historical file, filtered to Philadelphia records without an End Date. OSM places and road network: November 2025. This is not a live food directory. Absence from a source is not evidence that a store is closed or does not accept SNAP.</p><h3>What the route estimate means</h3><p>Shortest distance on a directed driving-road graph, divided by an illustrative 25 km/h, plus 5 minutes for parking. Routes snap to nearby road nodes with a maximum 150 m connector at each end. Traffic, turn restrictions, access-point barriers and parking availability are not modeled. Walking and transit networks are not included.</p><h3>Information and area counts</h3><p>The 6-field score counts name, address, category, phone, website and hours. It measures completeness, not truth. Tracts summarize observed records, not true coverage. Nine exact-name/address cross-source links are provisional; unlinked duplicates may remain.</p><p><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors · ODbL</a> · <a href="https://www.fns.usda.gov/snap/retailer-locator" target="_blank" rel="noopener">USDA SNAP</a> · <a href="data/manifest.json" target="_blank">Build provenance</a></p><p>Built from Philadelphia Food Desert Analysis by Tim Wen and Lingxuan Gao. New discovery experience: September 2026.</p>`);}
function download(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function study(){openModal(`<div class="eyebrow">PRODUCT STUDY / WORK IN PROGRESS</div><h2>From finding a place to choosing one.</h2><p><strong>Hypothesis:</strong> source-aware place cards and understandable travel estimates help people choose a feasible food destination with fewer external lookups. This hypothesis has not yet been user-tested.</p><h3>Try a task</h3><p>Start in University City. Find a historically SNAP-listed supermarket within a modeled 15-minute drive, inspect its information, and save it. Note what you still need to verify elsewhere.</p><h3>Optional session measurement</h3><p>Event logging is off by default. Enabling it records interaction names, result counts and categories in memory in this tab. Search text and coordinates are excluded. Export is manual; nothing is uploaded.</p><button id="consent" class="primary">${consent?'Stop session logging':'Start session logging'}</button><button id="export-events" class="secondary">Export ${events.length} session events</button><button id="export-reviews" class="secondary">Export local review flags</button><p><a href="docs/product-brief.md" target="_blank">Product brief</a> · <a href="docs/research-plan.md" target="_blank">Testing plan & metric definitions</a></p>`);$('#consent').onclick=()=>{consent=!consent;if(consent)track('session_start');studyRefresh();};$('#export-events').onclick=()=>download('fieldfare-session.json',{exportedAt:new Date().toISOString(),events});$('#export-reviews').onclick=()=>download('fieldfare-review-flags.json',storageGet('fieldfare.reviews',[]));}
function studyRefresh(){$('#modal').close();study();}
$('#about').onclick=about;$('#study').onclick=study;$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')&&e.offsetX<0)$('#modal').close();});
$('#search').oninput=e=>{state.query=e.target.value;limitRows=30;render();clearTimeout(track.timer);track.timer=setTimeout(()=>track('search_results',{count:visible.length}),500);};$('#category').onchange=e=>{state.category=e.target.value;limitRows=30;render();track('filter_change',{category:state.category,count:visible.length});};$('#snap').onchange=e=>{state.snap=e.target.checked;render();track('snap_filter',{enabled:state.snap,count:visible.length});};$('#sort').onchange=e=>{state.sort=e.target.value;render();};$('#limit').oninput=e=>{if(state.mode==='drive')state.limit=+e.target.value;else state.radius=+e.target.value;syncMode();render();};$('#limit').onchange=()=>track('budget_change',{mode:state.mode,count:visible.length});
$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;syncMode();render();if(active)showDetail(active,false);});$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#more').onclick=()=>{limitRows+=30;render();};$('#origin').onchange=e=>{if(presets[e.target.value]){origin=[...presets[e.target.value]];center=[...origin];compute();track('origin_change',{method:'preset'});}};$('#pick-origin').onclick=()=>{pick=!pick;$('#map-hint').textContent=pick?'Click the map to set your starting point':'Click a numbered place to explore';canvas.style.cursor=pick?'crosshair':'grab';};$('#zoom-in').onclick=()=>{scale=Math.min(180000,scale*1.3);scheduleDraw();};$('#zoom-out').onclick=()=>{scale=Math.max(14000,scale/1.3);scheduleDraw();};$('#recenter').onclick=()=>{center=[...origin];scale=67000;scheduleDraw();};
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,center:[...center]};moved=false;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)moved=true;if(moved){center=[drag.center[0]-dx/(scale*.767),drag.center[1]+dy/scale];scheduleDraw();}});canvas.addEventListener('pointerup',e=>{if(!drag)return;drag=null;if(moved)return;const rect=canvas.getBoundingClientRect(),pos=[e.clientX-rect.left,e.clientY-rect.top],point=unproject(pos);if(pick){if(!inGeometry(point,city)){toast('Choose a starting point inside Philadelphia.');return;}origin=point;center=[...point];$('#origin').value='custom';pick=false;canvas.style.cursor='grab';$('#map-hint').textContent='Click a numbered place to explore';compute();track('origin_change',{method:'map'});return;}if(state.tab==='areas'){const a=areas.find(a=>inGeometry(point,a.geometry));if(a){areaId=a.id;active=null;path=[];$('#detail').hidden=true;render();}return;}const hit=pins.findLast(p=>Math.hypot(p.x-pos[0],p.y-pos[1])<19);if(hit)showDetail(hit.p.id);});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(14000,Math.min(180000,scale*(e.deltaY>0?.9:1.1)));scheduleDraw();},{passive:false});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}if(e.key==='Escape'&&active){active=null;path=[];$('#detail').hidden=true;render();}});
async function init(){try{[places,areas,roads,city,manifest]=await Promise.all(['places','areas','roads','city','manifest'].map(name=>fetch(`./data/${name}.json`).then(r=>{if(!r.ok)throw new Error(`Cannot load ${name}`);return r.json();})));const ids=new Set(places.map(p=>p.id));for(const id of saved)if(!ids.has(id))saved.delete(id);areas.forEach(a=>a.count=places.filter(p=>p.area===a.id).length);places.forEach(p=>routes[p.id]={direct:meters(origin,p.point),distance:null,minutes:null});worker.postMessage({type:'init'});render();resize();}catch(error){$('#status').textContent='The data could not load. Start the local server and reload this page.';$('#results').innerHTML=`<div class="empty"><strong>Unable to load this field guide</strong>${escape(error.message)}<br>Run npm run dev, then open http://localhost:4173.</div>`;}}init();
